[platformio]
default_envs = board1

[env:base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -std=gnu++2a
    -std=c17
    -I include
    -I include/producers
    -I include/consumers
lib_deps =
    lvgl/lvgl@^8.4.0

[env:board1]
extends = env:base
board_build.cmake_extra_args =
    "-DIDF_COMPONENT_MANAGER=1"
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults"
    "-DBOARD=board1"

[env:board2]
extends = env:base
board_build.cmake_extra_args =
    "-DIDF_COMPONENT_MANAGER=1"
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults"
    "-DBOARD=board2"