; Structure:
;  - [common]       - Global settings (Platform, LDF, Monitor)
;  - [profile:*]    - Debug vs Release (Compiler optimization, Logging, etc..)
;  - [target:*]     - Target Board (Signal, Power, Dash)
;  - [vid:*]        - Vehicle ID (GP23, GP25EVO)
;  - [template:*]   - Required for assembling necessary CMake args (target + profile)
;  - [env:*]        - Final Environments (Template + Vehicle)

; ============================================================
; 1. COMMON SETTINGS
; ============================================================
[common]
platform = espressif32 @ ^6.12.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct
board_build.partitions = config/partitions/large_factory.csv
; Required for discovering external libraries (lvgl, esp_lcd) and the AcquisitionFramework
lib_ldf_mode = deep+
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17
build_flags = -std=gnu++2a  ;
; Allow the IDF Component Manager to run to fetch necessary libraries
cmake_manager = -DIDF_COMPONENT_MANAGER=1

; ============================================================
; 2. BUILD PROFILES
; ============================================================
[profile:debug]
build_type = debug
; Variable: Path to the debug sdkconfig
sdkconfig_profile = config/sdkconfig.debug

[profile:release]
build_type = release
sdkconfig_profile = config/sdkconfig.release

; ============================================================
; 3. HARDWARE TARGETS
; ============================================================
[target:signal_board]
build_flags = -DTARGET_SIGNAL_BOARD
subdir_target = signalboard

[target:power_board]
build_flags = -DTARGET_POWER_BOARD
subdir_target = powerboard

[target:dash_board]
build_flags = -DTARGET_DASHBOARD
subdir_target = dashboard

; ============================================================
; 4. VEHICLE DEFINITIONS
; ============================================================
[vid:gp23]
build_flags = -DVID=gp23

[vid:gp25evo]
build_flags = -DVID=gp25evo

; ============================================================
; 5. TEMPLATES
; ============================================================
; PlatformIO doesn't concatenate cmake args when defined multiple times, instead it overwrites them
; Therefore we must build the arguments in a single step

; --- Signal Board Templates ---
[template:signal_debug]
extends = common, profile:debug, target:signal_board
board_build.cmake_extra_args = 
    ${common.cmake_manager} 
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;${profile:debug.sdkconfig_profile}"
    "-DTARGET_SUBDIR=${target:signal_board.subdir_target}"

[template:signal_release]
extends = common, profile:release, target:signal_board
board_build.cmake_extra_args = 
    ${common.cmake_manager} 
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;${profile:release.sdkconfig_profile}" 
    "-DTARGET_SUBDIR=${target:signal_board.subdir_target}"

; --- Power Board Templates ---
[template:power_debug]
extends = common, profile:debug, target:power_board
board_build.cmake_extra_args = 
    ${common.cmake_manager} 
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;${profile:debug.sdkconfig_profile}" 
    "-DTARGET_SUBDIR=${target:power_board.subdir_target}"

[template:power_release]
extends = common, profile:release, target:power_board
board_build.cmake_extra_args = 
    ${common.cmake_manager} 
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;${profile:release.sdkconfig_profile}" 
    "-DTARGET_SUBDIR=${target:power_board.subdir_target}"

; --- Dashboard Templates ---
[template:dash_debug]
extends = common, profile:debug, target:dash_board
board_build.cmake_extra_args = 
    ${common.cmake_manager} 
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;${profile:debug.sdkconfig_profile}" 
    "-DTARGET_SUBDIR=${target:dash_board.subdir_target}"

[template:dash_release]
extends = common, profile:release, target:dash_board
board_build.cmake_extra_args = 
    ${common.cmake_manager} 
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;${profile:release.sdkconfig_profile}" 
    "-DTARGET_SUBDIR=${target:dash_board.subdir_target}"

; ============================================================
; 6. FINAL ENVIRONMENTS
; ============================================================

; --- GP23 Enviroments ---
[env:gp23-signal_board-debug]
extends = template:signal_debug, vid:gp23

[env:gp23-signal_board-release]
extends = template:signal_release, vid:gp23

[env:gp23-power_board-debug]
extends = template:power_debug, vid:gp23

[env:gp23-power_board-release]
extends = template:power_release, vid:gp23

[env:gp23-dash_board-debug]
extends = template:dash_debug, vid:gp23

[env:gp23-dash_board-release]
extends = template:dash_release, vid:gp23

; --- GP25EVO Envorinments ---
[env:gp25evo-signal_board-debug]
extends = template:signal_debug, vid:gp25evo

[env:gp25evo-signal_board-release]
extends = template:signal_release, vid:gp25evo

[env:gp25evo-power_board-debug]
extends = template:power_debug, vid:gp25evo

[env:gp25evo-power_board-release]
extends = template:power_release, vid:gp25evo

[env:gp25evo-dash_board-debug]
extends = template:dash_debug, vid:gp25evo

[env:gp25evo-dash_board-release]
extends = template:dash_release, vid:gp25evo

; ============================================================
; 7. Unit Testing
; ============================================================
[env:unit_testing_logic]
extends = common
build_type = debug
test_framework = unity
test_build_src = no
test_filter = test_logic
board_build.cmake_extra_args =
    ${common.cmake_manager}
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;config/sdkconfig.debug"
    "-DTARGET_SUBDIR=${target:signal_board.subdir_target}"

# NOTE: PlatformIO sucks. Using extends with more than 1 levels breaks things.
# Furthermore, test_filter parameter also breaks and cannot handle multiple test suites.
# Currently the best way to select the correct hardware unit test, is to add a runtime flag
# like this : "TEST_HW_XXX" where XXX is the module name (check the filename)
[env:unit_testing_hardware]
extends = common
build_type = debug
test_framework = unity
test_build_src = no
test_filter = test_hardware
build_flags = -D "TEST_HW_MCPWM"
board_build.cmake_extra_args =
    ${common.cmake_manager}
    "-DSDKCONFIG_DEFAULTS=config/sdkconfig.defaults;config/sdkconfig.debug"
    "-DTARGET_SUBDIR=${target:signal_board.subdir_target}"